networks:
  gitea:
    external: false

volumes:
  gitea-data:
    driver: local
    name: gitea-data
  gitea-config:
    driver: local
    name: gitea-config
  gitea-sql:
    driver: local
    name: gitea-sql
  gitea-runner:
    driver: local
    name: gitea-runner
  gitea-proxy:
    driver: local
    name: gitea-proxy

services:
  init-config:
    image: alpine
    volumes: 
      - gitea-data:/data
      - ./theme:/theme-src
    command: >
      sh -c '
        if [ ! -f /data/gitea/.theme_initialized ]; then
          cp -a /theme-src/. /data/gitea
          touch /data/gitea/.theme_initialized
        fi
      '

  server:
    image: docker.gitea.com/gitea:1.26.1
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__START_SSH_SERVER=false
      - GITEA__mailer__ENABLED=false
      - GITEA__database__DB_TYPE=mysql
      - GITEA__database__HOST=db:3306
      - GITEA__database__NAME=${DB__NAME}
      - GITEA__database__USER=${DB__USERNAME}
      - GITEA__database__PASSWD=${DB__PASSWORD}
      - GITEA__actions__ENABLED=true
      - GITEA__ui__THEMES=catppuccin-latte-rosewater,catppuccin-latte-flamingo,catppuccin-latte-pink,catppuccin-latte-mauve,catppuccin-latte-red,catppuccin-latte-maroon,catppuccin-latte-peach,catppuccin-latte-yellow,catppuccin-latte-green,catppuccin-latte-teal,catppuccin-latte-sky,catppuccin-latte-sapphire,catppuccin-latte-blue,catppuccin-latte-lavender,catppuccin-frappe-rosewater,catppuccin-frappe-flamingo,catppuccin-frappe-pink,catppuccin-frappe-mauve,catppuccin-frappe-red,catppuccin-frappe-maroon,catppuccin-frappe-peach,catppuccin-frappe-yellow,catppuccin-frappe-green,catppuccin-frappe-teal,catppuccin-frappe-sky,catppuccin-frappe-sapphire,catppuccin-frappe-blue,catppuccin-frappe-lavender,catppuccin-macchiato-rosewater,catppuccin-macchiato-flamingo,catppuccin-macchiato-pink,catppuccin-macchiato-mauve,catppuccin-macchiato-red,catppuccin-macchiato-maroon,catppuccin-macchiato-peach,catppuccin-macchiato-yellow,catppuccin-macchiato-green,catppuccin-macchiato-teal,catppuccin-macchiato-sky,catppuccin-macchiato-sapphire,catppuccin-macchiato-blue,catppuccin-macchiato-lavender,catppuccin-mocha-rosewater,catppuccin-mocha-flamingo,catppuccin-mocha-pink,catppuccin-mocha-mauve,catppuccin-mocha-red,catppuccin-mocha-maroon,catppuccin-mocha-peach,catppuccin-mocha-yellow,catppuccin-mocha-green,catppuccin-mocha-teal,catppuccin-mocha-sky,catppuccin-mocha-sapphire,catppuccin-mocha-blue,catppuccin-mocha-lavender
      - GITEA__ui__DEAFULT_THEME=catppuccin-latte-blue # colorblind friendly
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER__REGISTRATION_TOKEN}
    restart: always
    volumes:
      # - gitea-data:/data/gitea
      - gitea-data:/data
      - gitea-config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - gitea
    ports:
      # - "3010:3000"
      - "3020:22"
    depends_on:
      - init-config
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      retries: 3
      start_period: 5s
      timeout: 10s

  db:
    image: mysql:8
    container_name: gitea-mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB__ROOT_PASSWORD}
      - MYSQL_USER=${DB__USERNAME}
      - MYSQL_PASSWORD=${DB__PASSWORD}
      - MYSQL_DATABASE=${DB__NAME}
    networks:
      - gitea
    volumes:
      - gitea-sql:/var/lib/mysql

  runner:
    image: gitea/act_runner
    container_name: gitea-runner
    restart: always
    depends_on:
      server:
        condition: service_healthy
        restart: true
    volumes:
      - gitea-runner:/data
      - ./config/act_runner.yaml:/data/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitea
    environment:
      - CONFIG_FILE=/data/config.yaml
      - GITEA_INSTANCE_URL=http://server:3000
      - GITEA_RUNNER_REGISTRATION_TOKEN=${GITEA_RUNNER__REGISTRATION_TOKEN}
      - GITEA_RUNNER_NAME=DEFAULT
      - GITEA_RUNNER_EPHEMERAL=1

  caddy:
    image: caddy
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    volumes:
      - ./config/GiteaProxy-Caddyfile:/etc/caddy/Caddyfile
      - gitea-proxy:/data
      - gitea-proxy:/config
    networks:
      - gitea
    environment:
      - CADDY_DOMAIN=${CADDY_DOMAIN}
