container:
  network: gittea_gitea

runner:
  labels:
    - "ubuntu-latest:docker://docker.gitea.com/runner-images:ubuntu-latest-full"
    - "ubuntu-24.04:docker://docker.gitea.com/runner-images:ubuntu-24.04-full"
    - "ubuntu-22.04:docker://docker.gitea.com/runner-images:ubuntu-22.04-full"
